---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: debug-ui
  namespace: debug
spec:
  rules:
  - host: ui.debug.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-debug
          servicePort: 8000
