apiVersion: v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    app: debug-node3
  name: debug-node3
spec:
  replicas: 1
  selector:
    deploymentconfig: debug-node3
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: debug-node3
        deploymentconfig: debug-node3
      name: debug-node3
    spec:
      containers:
      - env:
        - name: PATH
          value: /opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rh/rh-php56/root/usr/bin
        image: bjdhub.haihangyun.com/library/debug:latest
        imagePullPolicy: Always
        name: debug-node3
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 125m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: test-node3
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
