apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: hello-os
  name: hello-os
spec:
  replicas: 1
  selector:
    deploymentconfig: hello-os
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: hello-os
        deploymentconfig: hello-os
    spec:
      containers:
      - env:
          image: openshift/hello-openshift:latest
        imagePullPolicy: Always
        name: hello-os
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
