global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.aliyun.com:25'
  smtp_from: 'zhanglianx111@aliyun.com'
  smtp_username: 'zhanglianx111'
  smtp_password: 'yannnji1208'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'baixin'
receivers:
- name: 'baixin'
  email_configs:
  - to: 'zhanglianxiang@aibank.com'
